# Resolve the issue of gl-portal redirecting to a local address

location /luci-static/ {
    root /www;
    if ( !-e $request_filename ) {
        return 418;
    }
}

location /ubus {
    return 307 /cgi-bin/luci/admin/ubus/;
}
