export default [
    "el-icon-platform-eleme",
    "el-icon-eleme",
    "el-icon-delete-solid",
    "el-icon-delete",
    "el-icon-s-tools",
    "el-icon-setting",
    "el-icon-user-solid",
    "el-icon-user",
    "el-icon-phone",
    "el-icon-phone-outline",
    "el-icon-more",
    "el-icon-more-outline",
    "el-icon-star-on",
    "el-icon-star-off",
    "el-icon-s-goods",
    "el-icon-goods",
    "el-icon-warning",
    "el-icon-warning-outline",
    "el-icon-question",
    "el-icon-info",
    "el-icon-remove",
    "el-icon-circle-plus",
    "el-icon-success",
    "el-icon-error",
    "el-icon-zoom-in",
    "el-icon-zoom-out",
    "el-icon-remove-outline",
    "el-icon-circle-plus-outline",
    "el-icon-circle-check",
    "el-icon-circle-close",
    "el-icon-s-help",
    "el-icon-help",
    "el-icon-minus",
    "el-icon-plus",
    "el-icon-check",
    "el-icon-close",
    "el-icon-picture",
    "el-icon-picture-outline",
    "el-icon-picture-outline-round",
    "el-icon-upload",
    "el-icon-upload2",
    "el-icon-download",
    "el-icon-camera-solid",
    "el-icon-camera",
    "el-icon-video-camera-solid",
    "el-icon-video-camera",
    "el-icon-message-solid",
    "el-icon-bell",
    "el-icon-s-cooperation",
    "el-icon-s-order",
    "el-icon-s-platform",
    "el-icon-s-fold",
    "el-icon-s-unfold",
    "el-icon-s-operation",
    "el-icon-s-promotion",
    "el-icon-s-home",
    "el-icon-s-release",
    "el-icon-s-ticket",
    "el-icon-s-management",
    "el-icon-s-open",
    "el-icon-s-shop",
    "el-icon-s-marketing",
    "el-icon-s-flag",
    "el-icon-s-comment",
    "el-icon-s-finance",
    "el-icon-s-claim",
    "el-icon-s-custom",
    "el-icon-s-opportunity",
    "el-icon-s-data",
    "el-icon-s-check",
    "el-icon-s-grid",
    "el-icon-menu",
    "el-icon-share",
    "el-icon-d-caret",
    "el-icon-caret-left",
    "el-icon-caret-right",
    "el-icon-caret-bottom",
    "el-icon-caret-top",
    "el-icon-bottom-left",
    "el-icon-bottom-right",
    "el-icon-back",
    "el-icon-right",
    "el-icon-bottom",
    "el-icon-top",
    "el-icon-top-left",
    "el-icon-top-right",
    "el-icon-arrow-left",
    "el-icon-arrow-right",
    "el-icon-arrow-down",
    "el-icon-arrow-up",
    "el-icon-d-arrow-left",
    "el-icon-d-arrow-right",
    "el-icon-video-pause",
    "el-icon-video-play",
    "el-icon-refresh",
    "el-icon-refresh-right",
    "el-icon-refresh-left",
    "el-icon-finished",
    "el-icon-sort",
    "el-icon-sort-up",
    "el-icon-sort-down",
    "el-icon-rank",
    "el-icon-loading",
    "el-icon-view",
    "el-icon-c-scale-to-original",
    "el-icon-date",
    "el-icon-edit",
    "el-icon-edit-outline",
    "el-icon-folder",
    "el-icon-folder-opened",
    "el-icon-folder-add",
    "el-icon-folder-remove",
    "el-icon-folder-delete",
    "el-icon-folder-checked",
    "el-icon-tickets",
    "el-icon-document-remove",
    "el-icon-document-delete",
    "el-icon-document-copy",
    "el-icon-document-checked",
    "el-icon-document",
    "el-icon-document-add",
    "el-icon-printer",
    "el-icon-paperclip",
    "el-icon-takeaway-box",
    "el-icon-search",
    "el-icon-monitor",
    "el-icon-attract",
    "el-icon-mobile",
    "el-icon-scissors",
    "el-icon-umbrella",
    "el-icon-headset",
    "el-icon-brush",
    "el-icon-mouse",
    "el-icon-coordinate",
    "el-icon-magic-stick",
    "el-icon-reading",
    "el-icon-data-line",
    "el-icon-data-board",
    "el-icon-pie-chart",
    "el-icon-data-analysis",
    "el-icon-collection-tag",
    "el-icon-film",
    "el-icon-suitcase",
    "el-icon-suitcase-1",
    "el-icon-receiving",
    "el-icon-collection",
    "el-icon-files",
    "el-icon-notebook-1",
    "el-icon-notebook-2",
    "el-icon-toilet-paper",
    "el-icon-office-building",
    "el-icon-school",
    "el-icon-table-lamp",
    "el-icon-house",
    "el-icon-no-smoking",
    "el-icon-smoking",
    "el-icon-shopping-cart-full",
    "el-icon-shopping-cart-1",
    "el-icon-shopping-cart-2",
    "el-icon-shopping-bag-1",
    "el-icon-shopping-bag-2",
    "el-icon-sold-out",
    "el-icon-sell",
    "el-icon-present",
    "el-icon-box",
    "el-icon-bank-card",
    "el-icon-money",
    "el-icon-coin",
    "el-icon-wallet",
    "el-icon-discount",
    "el-icon-price-tag",
    "el-icon-news",
    "el-icon-guide",
    "el-icon-male",
    "el-icon-female",
    "el-icon-thumb",
    "el-icon-cpu",
    "el-icon-link",
    "el-icon-connection",
    "el-icon-open",
    "el-icon-turn-off",
    "el-icon-set-up",
    "el-icon-chat-round",
    "el-icon-chat-line-round",
    "el-icon-chat-square",
    "el-icon-chat-dot-round",
    "el-icon-chat-dot-square",
    "el-icon-chat-line-square",
    "el-icon-message",
    "el-icon-postcard",
    "el-icon-position",
    "el-icon-turn-off-microphone",
    "el-icon-microphone",
    "el-icon-close-notification",
    "el-icon-bangzhu",
    "el-icon-time",
    "el-icon-odometer",
    "el-icon-crop",
    "el-icon-aim",
    "el-icon-switch-button",
    "el-icon-full-screen",
    "el-icon-copy-document",
    "el-icon-mic",
    "el-icon-stopwatch",
    "el-icon-medal-1",
    "el-icon-medal",
    "el-icon-trophy",
    "el-icon-trophy-1",
    "el-icon-first-aid-kit",
    "el-icon-discover",
    "el-icon-place",
    "el-icon-location",
    "el-icon-location-outline",
    "el-icon-location-information",
    "el-icon-add-location",
    "el-icon-delete-location",
    "el-icon-map-location",
    "el-icon-alarm-clock",
    "el-icon-timer",
    "el-icon-watch-1",
    "el-icon-watch",
    "el-icon-lock",
    "el-icon-unlock",
    "el-icon-key",
    "el-icon-service",
    "el-icon-mobile-phone",
    "el-icon-bicycle",
    "el-icon-truck",
    "el-icon-ship",
    "el-icon-basketball",
    "el-icon-football",
    "el-icon-soccer",
    "el-icon-baseball",
    "el-icon-wind-power",
    "el-icon-light-rain",
    "el-icon-lightning",
    "el-icon-heavy-rain",
    "el-icon-sunrise",
    "el-icon-sunrise-1",
    "el-icon-sunset",
    "el-icon-sunny",
    "el-icon-cloudy",
    "el-icon-partly-cloudy",
    "el-icon-cloudy-and-sunny",
    "el-icon-moon",
    "el-icon-moon-night",
    "el-icon-dish",
    "el-icon-dish-1",
    "el-icon-food",
    "el-icon-chicken",
    "el-icon-fork-spoon",
    "el-icon-knife-fork",
    "el-icon-burger",
    "el-icon-tableware",
    "el-icon-sugar",
    "el-icon-dessert",
    "el-icon-ice-cream",
    "el-icon-hot-water",
    "el-icon-water-cup",
    "el-icon-coffee-cup",
    "el-icon-cold-drink",
    "el-icon-goblet",
    "el-icon-goblet-full",
    "el-icon-goblet-square",
    "el-icon-goblet-square-full",
    "el-icon-refrigerator",
    "el-icon-grape",
    "el-icon-watermelon",
    "el-icon-cherry",
    "el-icon-apple",
    "el-icon-pear",
    "el-icon-orange",
    "el-icon-coffee",
    "el-icon-ice-tea",
    "el-icon-ice-drink",
    "el-icon-milk-tea",
    "el-icon-potato-strips",
    "el-icon-lollipop",
    "el-icon-ice-cream-square",
    "el-icon-ice-cream-round",
    "iconfont icon-preview",
    "iconfont icon-edgerouter",
    "iconfont icon-clear",
    "iconfont icon-camera",
    "iconfont icon-pad",
    "iconfont icon-watch",
    "iconfont icon-television",
    "iconfont icon-smartappliances",
    "iconfont icon-games",
    "iconfont icon-gateway",
    "iconfont icon-phone",
    "iconfont icon-computer",
    "iconfont icon-printer",
    "iconfont icon-sound",
    "iconfont icon-laptop",
    "iconfont icon-fan-setting",
    "iconfont icon-switch",
    "iconfont icon-battery",
    "iconfont icon-bolt",
    "iconfont icon-led",
    "iconfont icon-vlan",
    "iconfont icon-tflash",
    "iconfont icon-flash",
    "iconfont icon-clock",
    "iconfont icon-thread",
    "iconfont icon-toggle",
    "iconfont icon-play",
    "iconfont icon-stop",
    "iconfont icon-palette",
    "iconfont icon-sort-down",
    "iconfont icon-eject",
    "iconfont icon-clients",
    "iconfont icon-upload",
    "iconfont icon-delete",
    "iconfont icon-edit",
    "iconfont icon-check",
    "iconfont icon-network",
    "iconfont icon-copy",
    "iconfont icon-export",
    "iconfont icon-wlan-client",
    "iconfont icon-lan-client",
    "iconfont icon-warning",
    "iconfont icon-plus",
    "iconfont icon-internet-ethernet",
    "iconfont icon-internet-cellular",
    "iconfont icon-internet-repeater",
    "iconfont icon-internet-tethering",
    "iconfont icon-wifi-2g",
    "iconfont icon-guest-wifi-2g",
    "iconfont icon-wifi-5g",
    "iconfont icon-guest-wifi-5g",
    "iconfont icon-arrow-up",
    "iconfont icon-action",
    "iconfont icon-block",
    "iconfont icon-speed",
    "iconfont icon-speed-limit",
    "iconfont icon-application",
    "iconfont icon-firewall",
    "iconfont icon-upgrade",
    "iconfont icon-setting",
    "iconfont icon-vpn",
    "iconfont icon-internet",
    "iconfont icon-wireless",
    "iconfont icon-lan",
    "iconfont icon-show",
    "iconfont icon-hide",
    "iconfont icon-tethering",
    "iconfont icon-vpn1",
    "iconfont icon-reboot",
    "iconfont icon-error",
    "iconfont icon-success",
    "iconfont icon-lock",
    "iconfont icon-wrong",
    "iconfont icon-info",
    "iconfont icon-compress",
    "iconfont icon-expand",
    "iconfont icon-chevron-down",
    "iconfont icon-envelope",
    "iconfont icon-tools",
    "iconfont icon-guest-wifi",
    "iconfont icon-thermometer-half",
    "iconfont icon-wifi",
    "iconfont icon-tor",
    "iconfont icon-idsips",
    "iconfont icon-adguard",
    "iconfont icon-ipv6",
    "iconfont icon-modem",
    "iconfont icon-question-circle",
    "iconfont icon-redo-alt",
    "iconfont icon-sign-out-alt",
    "iconfont icon-search",
    "iconfont icon-collapse",
    "iconfont icon-loading",
    "iconfont icon-pretense",
    "iconfont icon-qrcode",
    "iconfont icon-filter",
    "iconfont icon-authentication",
    "iconfont icon-ovpn-tap",
    "iconfont icon-dfs",
    "iconfont icon-modem-reboot",
    "iconfont icon-cellular",
    "iconfont icon-clock-rotate-left",
    "iconfont icon-cellular-lock",
    "iconfont icon-lock-open",
    "iconfont icon-simcard",
    "iconfont icon-full-signal",
    "iconfont icon-save",
    "iconfont icon-manageprofiles",
    "iconfont icon-bluetooth",
    "iconfont icon-access",
    "iconfont icon-shield-regular-full",
    "iconfont icon-bolt-regular-full",
    "iconfont icon-globe-regular-full",
    "iconfont icon-gift-regular-full",
    "iconfont icon-version",
    "iconfont icon-share-from-square-regular-full",
    "iconfont icon-monitor-waveform-regular-full",
    "iconfont icon-cloud-question-regular-full",
    "iconfont icon-folder-gear-regular-full",
    "iconfont icon-detect",
    "iconfont icon-reset",
    "iconfont icon-remote-connection",
    "iconfont icon-block-wan",
    "iconfont icon-grid-menu",
    "iconfont icon-dpi-enigine",
    "iconfont icon-dpi-database",
    "iconfont icon-dpi-version",
    "iconfont icon-lan-guest",
    "iconfont icon-lan-customize",
    "iconfont icon-lan-iot",
    "iconfont icon-port-vlan",
    "iconfont icon-port-sfp",
    "iconfont icon-offline-devices",
    "iconfont icon-circle-arrow-up",
    "iconfont icon-book-solid-full",
    "iconfont icon-lock-keyhole-solid-full",
    "iconfont icon-order",
    "iconfont icon-wifi-guest",
    "iconfont icon-wifi-iot",
    "iconfont icon-easymesh",
    "iconfont icon-wifi-sharp-solid-full-shown",
    "iconfont icon-wifi-sharp-solid-full",
    "iconfont icon-lock-keyhole-regular-full",
    "iconfont icon-lock-keyhole-open-regular-full",
    "iconfont icon-iot-wifi",
    "iconfont icon-wifi-iot-5g",
    "iconfont icon-wifi-iot-2g",
    "iconfont icon-radar-regular-full",
    "iconfont icon-pen-field-regular-full",
    "iconfont icon-image-solid-full",
    "iconfont icon-add-node",
    "iconfont icon-chart-network",
    "iconfont icon-list",
    "iconfont icon-copy2",
    "iconfont icon-edit-pen",
    "iconfont icon-moon-stars",
    "iconfont icon-sun-haze",
    "iconfont icon-security",
    "iconfont icon-adult",
    "iconfont icon-clear2",
    "iconfont icon-virus",
    "iconfont icon-playing-cards",
    "iconfont icon-droplet-regular",
    "iconfont icon-timer-regular",
    "iconfont icon-clock-regular",
    "iconfont icon-car",
    "iconfont icon-home",
    "iconfont icon-power-switch",
    "iconfont icon-list-dropdown-light-full",
    "iconfont icon-guest-wifi-mlo-2g",
    "iconfont icon-chart-waterfall-regular-full",
    "iconfont icon-shield-heart-regular-full",
    "iconfont icon-gauge-simple-high-regular-full",
    "iconfont icon-USB",
    "iconfont icon-USB-client",
    "iconfont icon-guest-wifi-mlo-6g",
    "iconfont icon-wifi-mlo-5g",
    "iconfont icon-guest-wifi-mlo-5g",
    "iconfont icon-wifi-mlo-2g",
    "iconfont icon-wifi-mlo-6g",
    "iconfont icon-smartinternet",
    "iconfont icon-sort",
    "iconfont icon-triage",
    "iconfont icon-android",
    "iconfont icon-macos",
    "iconfont icon-apple",
    "iconfont icon-windows",
    "iconfont icon-download",
    "iconfont icon-DNS3",
    "iconfont icon-DNS-Dashboard",
    "iconfont icon-vpnofff",
    "iconfont icon-arrow",
    "iconfont icon-arrow-solid",
    "iconfont icon-set-config",
    "iconfont icon-headset",
    "iconfont icon-operator",
    "iconfont icon-mailbox-solid",
    "iconfont icon-increase-decrease",
    "iconfont icon-nas",
    "iconfont icon-network-switch",
    "iconfont icon-network-server",
    "iconfont icon-guest-wifi-mlo",
    "iconfont icon-wifi-mlo",
    "iconfont icon-wifi-6g",
    "iconfont icon-guest-wifi-6g",
    "iconfont icon-fire-flame-curved-solid",
    "iconfont icon-aw-gateway",
    "iconfont icon-aw-cloud-gateway",
    "iconfont icon-aw-router",
    "iconfont icon-lead",
    "iconfont icon-lead-vpn",
    "iconfont icon-port",
    "iconfont icon-cloud",
    "iconfont icon-cloud-services",
    "iconfont icon-message",
    "iconfont icon-earth-asia",
    "iconfont icon-user",
    "iconfont icon-server",
    "iconfont icon-link"
]
